version: 2.1
orbs:
  node: circleci/node@1.1.6
  jira: circleci/jira@1.1.7
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm audit
            - run: npm test
      - run:
          name: Deploy Master to Heroku
          command:
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$FAIRY_CIRCLE_API.git master 
  
workflows:
    build-and-test:
      jobs:
        - build-and-test
        -  build:
          post-steps:
            - jira/notify
