version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm audit
            - run: npm test
  deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command:
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
     
workflows:
    build-and-test:
      jobs:
        - build-and-test
